### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by gramss** [markusb/uDMX-linux#2]
Hi,

could you please issue a license for your work, so it is clear if it can be commercially etc. used?

Thanks!

**Comment by markusb** [comment]
I'm a bit in a bind. My code is derived for code, originally hosted on http://udmx.googlecode.com/. This code was migrated to https://github.com/mirdej/udmx when google code was closed. The original code has no license either, so I can not really decide how this code should be licensed without potentially violating someones rights.

I don't know how to contact the author either. Github seems not to offer a way to send someone a message.

**Comment by markusb** [comment]
The original authos replied to my issue and told me it is GPL2.0.
I'lve added the license.
